// <auto-generated />
namespace BabyBook.Api.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class indicealumnofecha : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(indicealumnofecha));
        
        string IMigrationMetadata.Id
        {
            get { return "201408191147269_indicealumnofecha"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
